---
- name: "Install Tailscale"
  # Playbook requires facts to collect the distribution:
  gather_facts: true
  hosts:
    - storage
    - compute
  roles:
    - artis3n.tailscale
  vars:
    # We perform authentication after the fact, manually
    tailscale_up_skip: true
- name: "Configure vm server"
  gather_facts: false
  hosts: rack19
  roles:
    - vmhost
- name: "Configure storage server"
  gather_facts: false
  hosts: storage
  vars:
    prometheus_agent_mode: true
  roles:
    - storage
    - role: backup
      tags: backup
- name: "Configure Prometheus"
  import_playbook: prometheus/playbook.yaml
- name: "Configure compute services"
  import_playbook: compute.yaml
- name: "Configure reMarkable and relations"
  import_playbook: remarkable/remarkable.yaml
