---
- name: "Install fallback key"
  hosts: all
  gather_facts: false
  roles: [login]
- name: "Install public-VM configuration"
  hosts:
    - pvm0
  roles:
    - homelab-public
- name: "Install BIND and configuration"
  hosts:
    - pvm0
    - pvm1
    - pvm2
  roles:
    - dns
- name: "Install Samba client config"
  hosts:
    - localhost
    - compute
  roles:
    - storage-client
- name: "Install Tailscale"
  # Playbook requires facts to collect the distribution:
  gather_facts: true
  hosts:
    - storage
    - compute
  roles:
    - artis3n.tailscale
  vars:
    # We perform authentication after the fact, manually
    tailscale_up_skip: true
- name: "Configure UPS response"
  gather_facts: false
  hosts:
    - rack19
  roles:
    - upsclient
- name: "Configure vm server"
  gather_facts: false
  hosts: rack19
  roles:
    - vmhost
- name: "Configure storage server"
  gather_facts: false
  hosts: storage
  vars:
    prometheus_agent_mode: true
  roles:
    - storage
    - backup
- name: "Install misc storage services"
  hosts: [storage]
  roles: 
    - miniflux
    - reading-list
  gather_facts: false
- name: "Configure Prometheus"
  import_playbook: prometheus/playbook.yaml
- name: "Configure compute services"
  import_playbook: compute.yaml
- name: "Configure reMarkable and relations"
  import_playbook: remarkable/remarkable.yaml
- name: "Install Samba client config"
  hosts:
    - localhost
  roles:
    - storage-client

