---
- name: "Configure ipmi host server"
  gather_facts: false
  hosts: rack18
  roles:
    - ipmihost
- name: "Configure vm server"
  gather_facts: false
  hosts: rack19
  roles:
    - vmhost
- name: "Configure storage server"
  gather_facts: false
  hosts: storage
  roles:
    - storage

- name: "Install Tailscale"
  gather_facts: false
  hosts:
    - storage
    - ipmihost
  roles:
    - artis3n.tailscale
  vars:
    tailscale_up_skip: true
