---
- name: "Install Tailscale"
  # Playbook requires facts to collect the distribution:
  gather_facts: true
  hosts:
    - storage
    - ipmihost
  roles:
    - artis3n.tailscale
  vars:
    # We perform authentication after the fact, manually
    tailscale_up_skip: true
- name: "Configure ipmi host server"
  gather_facts: false
  hosts: rack18
  roles:
    - ipmihost
- name: "Configure vm server"
  gather_facts: false
  hosts: rack19
  roles:
    - vmhost
- name: "Configure storage server"
  gather_facts: false
  hosts: storage
  roles:
    - storage

