---
- name: "Debian package update and upgrade"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Upgrade Debian packages"
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: true

