- name: "Install packages"
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    pkg:
      - unattended-upgrades
      - powermgmt-base
- name: "Install configuration"
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: >
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

