- name: "Remove cruft"
  become: true
  ansible.builtin.apt:
    state: absent
    cache_valid_time: 3600
    pkg:
      - google-cloud-cli
      - google-cloud-anthoscli
- name: "Install apt packages"
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    pkg:
      - bind9
      - dnsutils
      - fail2ban
      - tcpdump
      - mtr-tiny
- name: "Make /etc/bind subdirectory"
  become: true
  ansible.builtin.file:
    state: directory
    mode: '0755'
    owner: bind
    group: bind
    path: '/etc/bind/{{ dns_role }}'
- name: "Add files to /etc"
  become: true
  with_fileglob:
    - '{{ dns_role }}/*'
  ansible.builtin.copy:
    decrypt: true
    mode: '0644'
    src: '{{ item }}'
    dest: "/etc/bind/{{ dns_role }}/{{ item | basename }}"
- name: "Add zone links to /var"
  become: true
  with_fileglob:
    - '{{ dns_role }}/*.db'
  ansible.builtin.file:
    state: link
    mode: '0644'
    src: '/etc/bind/{{ dns_role }}/{{ item | basename }}'
    # Must be in /var due to AppArmor:
    # https://lists.isc.org/mailman/htdig/bind-users/2020-September/103706.html
    dest: "/var/lib/bind/{{ dns_role }}/{{ item | basename }}"
- name: "Un-include options file"
  become: true
  ansible.builtin.lineinfile:
    regexp: '^[ ]*include .*/etc/bind/named\.conf\.options.*'
    state: "absent"
    path: /etc/bind/named.conf
- name: "Include configuration file(s)"
  become: true
  ansible.builtin.lineinfile:
    line: 'include "/etc/bind/{{ dns_role }}/*.conf";'
    path: /etc/bind/named.conf
- name: "Reload configuration"
  become: true
  # Lightest possible config reload:
  ansible.builtin.command: 'pkill -HUP named'
    

