- name: "Remove cruft"
  become: true
  ansible.builtin.apt:
    state: absent
    cache_valid_time: 3600
    pkg:
      - google-cloud-cli
      - google-cloud-anthoscli
- name: "Install apt packages"
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    pkg:
      - bind9
      - dnsutils
      - fail2ban
      - tcpdump
      - mtr-tiny
- name: "Add zone files to /var"
  become: true
  loop: '{{ dns_roles | flatten(levels=1) }}'
  ansible.builtin.copy:
    decrypt: true
    mode: '0644'
    src: '{{ item }}/'
    # Must be in /var due to AppArmor:
    # https://lists.isc.org/mailman/htdig/bind-users/2020-September/103706.html
    dest: "/var/lib/bind/{{ item }}"
- name: "Make /etc/bind subdirectory"
  become: true
  loop: '{{ dns_roles | flatten(levels=1) }}'
  ansible.builtin.file:
    state: directory
    mode: '0755'
    owner: bind
    group: bind
    path: '/etc/bind/{{ item }}'
- name: "Add named config to /etc"
  become: true
  loop: '{{ dns_roles | flatten(levels=1) }}'
  ansible.builtin.copy:
    decrypt: true
    mode: '0644'
    owner: bind
    group: bind
    src: '{{ item }}/named.conf'
    # Alas, needs to be outside of etc/ due to AppArmor:
    # https://lists.isc.org/mailman/htdig/bind-users/2020-September/103706.html
    dest: "/etc/bind/{{ item }}/named.conf"
- name: "Un-include options file"
  become: true
  ansible.builtin.lineinfile:
    regexp: '^[ ]*include .*/etc/bind/named\.conf\.options.*'
    state: "absent"
    path: /etc/bind/named.conf
- name: "Include configuration file(s)"
  become: true
  loop: '{{ dns_roles | flatten(levels=1) }}'
  ansible.builtin.lineinfile:
    line: 'include "/etc/bind/{{ item }}/*.conf";'
    path: /etc/bind/named.conf
- name: "Reload configuration"
  become: true
  # Lightest possible config reload:
  ansible.builtin.command: 'pkill -HUP named'
    

