---
- name: "Configure reMarkable 2 tablet"
  hosts:
    - remarkable
  vars_files:
    - vars.yaml
  gather_facts: false
  tasks:
    - name: "Bootstrap SSH"
      local_action: ansible.builtin.command ./ssh.sh {{ inventory_hostname }}
    - name: "Install/update Tailscale"
      local_action: ansible.builtin.command ./tailscale.sh {{ inventory_hostname }}
    - name: "Install/update syncthing"
      local_action: ansible.builtin.command ./syncthing.sh {{ inventory_hostname }}

