#!/bin/bash

# Bang-bang control for system fans.
# Based on https://gist.github.com/qlyoung/44282a8283879d967b0c4314e7d4fb82,
# but with controls from https://forums.servethehome.com/index.php?resources/supermicro-x9-x10-x11-fan-speed-control.20/
# (which match what I observe.)


# At startup, switch to the "full" fan control- briefly:
ipmitool raw 0x30 0x45 1
# And get hwmon for drives:
modprobe drivetemp

# i350bb in particular runs hot, around 50
MAXTEMP=52

# Upper fan limit, in percent
FAST_PCT=25
# Lower fan limit, in percent
SLOW_PCT=8

# Convert from percentage to byte
UPPER="$(( FAST_PCT * 255 / 100 ))"
LOWER="$(( SLOW_PCT * 255 / 100 ))"

SAMPLES="/tmp/fanbang"
# Then periodically run at "fast" or "low":
while true
do
  echo >&2 "Starting thermal sampling cycle; threshold $MAXTEMP degrees C"
  # Collect aggregate data:
  echo -n >"$SAMPLES"
  ipmitool sdr type temperature \
    | grep ' ok ' \
    | sed -n 's/^\([^|]*\).*|[^|0-9]*\([0-9]\+\)[^|]*$/IPMI \1 : \2/p' \
    | tr -s '[:space:]' \
    >>"$SAMPLES"
  ls /sys/class/hwmon/*/temp*_input \
  | while read INPUT
  do
    NUM="$(basename $INPUT | grep -o '[0-9]')"
    cat \
      "$(dirname $INPUT)/name" \
     | tr '\r\n' ' ' >>"$SAMPLES"
    LABEL="$(dirname $INPUT)/temp${NUM}_label" 
    if test -f "$LABEL"
    then
      cat "$LABEL" | tr '\r\n' ' ' >>"$SAMPLES"
    fi
    echo ": $(( $(cat $INPUT) / 1000 ))" >>"$SAMPLES"
  done

  THROTTLE=false
  while read LINE
  do
    VALUE="$(echo "$LINE" | cut -d':' -f2 | tr -d '[:space:]')"
    if test -n "$VALUE" && test "$VALUE" -ge "$MAXTEMP"
    then
      echo >&2 "Throttling from input $(echo "$LINE" | cut -d':' -f1): $VALUE degrees C"
      THROTTLE=true
    fi
  done <"$SAMPLES"
  if test "$THROTTLE" = "true"
  then
    echo >&2 "Fast fan: ${FAST_PCT}%"
    ipmitool raw 0x30 0x70 0x66 0x01 0x00 "$UPPER" >/dev/null
  else
    echo >&2 "Slow fan: ${SLOW_PCT}%"
    ipmitool raw 0x30 0x70 0x66 0x01 0x00 "$LOWER" >/dev/null
  fi
  sleep 10
done

