- name: "Install user-friendly packages"
  become: true
  ansible.builtin.apt:
    pkg:
      - cmatrix
      - man
      - tmux
      - zsh
- name: "Change user shell to zsh"
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /bin/zsh

