- name: "Install zfs support"
  ansible.builtin.include_tasks: zfs.yaml
- name: "Install second interface"
  become: true
  ansible.builtin.copy:
    src: "vlan2.network"
    dest: /etc/systemd/network/10-vlan2.network
    mode: 0644
- name: "Create storage-access group"
  become: true
  ansible.builtin.group:
    name: storage-access
- name: "Create storage-access user"
  become: true
  ansible.builtin.user:
    name: storage-access
    groups:
      - storage-access
    password: "!"
    password_lock: true
    shell: "/usr/bin/false"
- name: "Install syncthing"
  ansible.builtin.include_tasks: syncthing.yaml
- name: "Install network filesystem servers"
  ansible.builtin.include_tasks: servers.yaml
- name: "Install navidrome"
  ansible.builtin.include_tasks: navidrome.yaml
- name: "Install syncthing"
  ansible.builtin.include_tasks: syncthing.yaml

