- name: "Install zfs support"
  ansible.builtin.include_tasks: zfs.yaml
- name: "Install backup support"
  ansible.builtin.include_tasks: backup.yaml
- name: "Install network filesystem servers"
  ansible.builtin.include_tasks: servers.yaml



