- name: "Install zfs support"
  ansible.builtin.include_tasks: zfs.yaml
- name: "Create storage-access group"
  become: true
  ansible.builtin.group:
    name: storage-access
- name: "Install syncthing"
  ansible.builtin.include_tasks: syncthing.yaml
- name: "Install backup support"
  ansible.builtin.include_tasks: backup.yaml
- name: "Install network filesystem servers"
  ansible.builtin.include_tasks: servers.yaml
- name: "Install navidrome"
  ansible.builtin.include_tasks: navidrome.yaml
- name: "Install syncthing"
  ansible.builtin.include_tasks: syncthing.yaml



