- name: "Include navidrome version"
  ansible.builtin.include_vars:
    file: navidrome.yaml
- name: "Prepare navidrome group"
  become: true
  ansible.builtin.group:
    name: navidrome
- name: "Prepare navidrome user"
  become: true
  ansible.builtin.user:
    name: navidrome
    group: navidrome
    groups:
      - storage-access
    password: "!"
    password_lock: true
- name: "Prepare packages for navidrome"
  become: true
  ansible.builtin.apt:
    pkg:
      - ffmpeg
      - flac
- name: "Prepare directories for navidrome"
  become: true
  with_items:
    - "/opt/navidrome"
    - "/var/lib/navidrome"
  ansible.builtin.file:
    owner: navidrome
    group: navidrome
    path: "{{ item }}"
    state: directory
- name: "Download and expand navidrome archive"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/navidrome/navidrome/releases/download/v{{ navidrome_version }}/navidrome_{{ navidrome_version }}_Linux_x86_64.tar.gz"
    remote_src: true
    dest: "/opt/navidrome"
    owner: navidrome
    group: navidrome
- name: "Install navidrome config"
  become: true
  with_items:
    - var/lib/navidrome/navidrome.toml
  ansible.builtin.copy:
    src: "navidrome/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
    owner: navidrome
- name: "Install navidrome unit"
  become: true
  with_items:
    - etc/systemd/system/navidrome.service
  ansible.builtin.copy:
    src: "navidrome/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
- name: "Run Navidrome"
  become: true
  ansible.builtin.systemd:
    name: navidrome
    daemon_reload: true
    state: restarted
    enabled: yes
- name: "Propagate tailscale"
  become: true
  ansible.builtin.command:
    cmd: "tailscale serve --bg --https 4533 http://127.0.0.1:4532"

