- name: "Install network filesystem servers"
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    pkg:
      - nfs-kernel-server
      - samba
      - samba-client
- name: "Configure Samba"
  become: true
  ansible.builtin.copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    mode: 0644
- name: "Restart Samba"
  become: true
  ansible.builtin.systemd:
    name: smbd
    state: restarted

