- name: "Install fanbang binary"
  become: true
  ansible.builtin.copy:
    src: fanctl/fanbang
    dest: /usr/local/bin/fanbang
    mode: 0544
- name: "Install fanctl unit"
  become: true
  ansible.builtin.copy:
    src: fanctl/fanctl.service
    dest: /etc/systemd/system/fanctl.service
- name: "Restart fanctl"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: fanctl
    enabled: true
    state: restarted

