- name: "Install fanbang binary"
  become: true
  ansible.builtin.copy:
    src: fanctl/fanbang
    dest: /usr/local/bin/fanbang
- name: "Install fanbang unit"
  become: true
  ansible.builtin.copy:
    src: fanctl/fanbang.service
    dest: /etc/systemd/system/fanbang.service
- name: "Restart apcupsd"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: fanbang
    enabled: true
    state: restarted

