- name: "Install ipmitool"
  become: true
  ansible.builtin.apt:
    pkg:
      - ipmitool
- name: "Proxmox config backup"
  ansible.builtin.include_tasks: proxmox-backup.yaml
- name: "UPS response"
  ansible.builtin.include_tasks: power.yaml
- name: "Fan control"
  ansible.builtin.include_tasks: fanctl.yaml

