- name: "Disable unit"
  become: true
  ignore_errors: true
  ansible.builtin.systemd:
    name: buildgrid
    state: stopped
    enabled: false
- name: "Disable tailscale"
  become: true
  ansible.builtin.command:
    cmd: "tailscale serve reset"
- name: "Remove source files"
  become: true
  with_items:
    - "{{ buildgrid_dir }}"
    - "{{ buildgrid_state }}"
    - "/etc/systemd/system/buildgrid.service"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
- name: "Remove user"
  become: true
  ansible.builtin.user:
    name: buildgrid
    state: absent
    remove: true
- name: "Remove group"
  become: true
  ansible.builtin.group:
    name: buildgrid
    state: absent

