- name: "Install DHCP server"
  become: true
  ansible.builtin.apt:
    pkg:
      - isc-dhcp-server
      - isc-dhcp-dev
- name: "Provide DHCPd configuration"
  become: true
  ansible.builtin.copy:
    dest: /etc/dhcp/dhcpd.conf
    src: dhcpd.conf
- name: "Provide isc-dhcp-server command-line config"
  become: true
  ansible.builtin.copy:
    dest: /etc/default/isc-dhcp-server
    src: isc-dhcp-server
- name: "Kill dhcpd"
  become: true
  ignore_errors: true # pretty flaky
  ansible.builtin.shell: "pkill dhcpd; rm /var/run/dhcpd.pid"
- name: "Restart DHCP server"
  become: true
  ignore_errors: true # pretty flaky
  ansible.builtin.systemd:
    name: isc-dhcp-server
    state: restarted

