- name: "Mount qboot"
  become: true
  ansible.posix.mount:
    boot: true
    state: mounted
    path: /mnt/qboot
    fstype: ext4
    src: /dev/disk/by-label/QBOOTUSB
- name: "Install ipmitool"
  become: true
  ansible.builtin.apt:
    pkg:
      - ipmitool
- name: "Configure network"
  ansible.builtin.include_tasks: network.yaml
- name: "Configure DHCP"
  ansible.builtin.include_tasks: dhcp.yaml
- name: "Configure UPS"
  ansible.builtin.include_tasks: power.yaml

