# - name: "Update baseline packages"
#   become: true
#   ansible.builtin.apt:
#     update_cache: true
#     cache_valid_time: 3600
#     upgrade: true
# - name: "Mount qboot"
#   become: true
#   ansible.posix.mount:
#     boot: true
#     state: mounted
#     path: /mnt/qboot
#     fstype: vfat
#     src: /dev/disk/by-partlabel/QBOOTUSB
- name: "Configure static IP"
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/network/
    src: network/
- name: "Restart networkd"
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
- name: "Install DHCP server"
  become: true
  ansible.builtin.apt:
    pkg:
      - isc-dhcp-server
      - isc-dhcp-dev
      - ipmitool
- name: "Provide DHCP server configuration"
  become: true
  ansible.builtin.copy:
    dest: /etc/dhcp/dhcpd.conf
    src: dhcpd.conf
- name: "Restart DHCP server"
  become: true
  ansible.builtin.systemd:
    name: isc-dhcp-server
    state: restarted

