#!/bin/sh

set -eux

# Install stage:
python3 -m venv .
. bin/activate
python3 -m pip install wheel

python3 -m pip install \
  homeassistant=={{ homeassistant_version }} \
  home-assistant-frontend=={{ homeassistant_fe_version }}

exec hass
