- name: "Install postgresql"
  become: true
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2 # postgres python support, for modules below
      - acl # setfacl, to allow Ansible to become postgres
- name: "Set up miniflux user"
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: miniflux
    password: "{{ miniflux_password }}"
- name: "Set up miniflux database"
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: miniflux
    owner: miniflux
- name: "Add hstore, for migration"
  become: true
  become_user: postgres
  community.postgresql.postgresql_ext:
    db: miniflux
    name: hstore
- name: "Install miniflux config file"
  become: true
  ansible.builtin.template:
    src: miniflux.conf
    dest: /etc/miniflux.conf
    owner: miniflux
    group: miniflux
    mode: "0600"
- name: "Install miniflux"
  become: true
  ansible.builtin.apt:
    deb: https://github.com/miniflux/v2/releases/download/2.1.3/miniflux_2.1.3_amd64.deb
- name: "Restart miniflux"
  become: true
  ansible.builtin.systemd_service:
    name: miniflux
    enabled: true
    state: restarted
# Instructions indicate to manually -create-admin, then restart the service.
# TODO: Put all these services behind an HTTP proxy.
- name: "Proxy GUI over HTTPS"
  become: true
  ansible.builtin.command:
    cmd: "tailscale serve --bg --https 8888 http://127.0.0.1:8888"

